env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
ignorePatterns: ["test.js"]
rules: {
  "import/no-extraneous-dependencies": ["error", {"devDependencies": true}]
}
